---
# tasks file for journald-persistent
   
- name: Create /var/log/journal
  file: 
    path: /var/log/journal
    state: directory
    owner: root
    group: root

- name: Configures /etc/systemd/journald.conf
  lineinfile:
    path: /etc/systemd/journald.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - { line: 'SystemMaxUse=100M', regexp: '^SystemMaxUse=.*' }
    - { line: 'Storage=persistent', regexp: '^Storage=.*' }
  notify: "Restart Journald"

