---
dependencies: []

galaxy_info:
  role_name: repo-epel
  author: geerlingguy
  description: EPEL repository for RHEL/CentOS.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.10
  platforms:
    # I begrudgingly support EL here, only because EPEL is also
    # critical to use of many projects on downstream projects.
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - packaging
    - epel
    - repository
    - repo
    - redhat
    - centos
    - rhel
