---
- hosts: localhost
  connection: local
  become: yes

  vars_prompt:
    - name: username
      prompt: What is your RHEL username?
      private: false

    - name: password
      prompt: What is your RHEL password?

  tasks:

    - name: Disable epel repos
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob: /etc/yum.repos.d/epel*

    - name: Check subscription status
      command: subscription-manager service-level
      register: subscription_status
      changed_when: false
      check_mode: false

    - name: Register with Red Hat subscription
      redhat_subscription:
        username: "{{ username }}"
        password: "{{ password }}"
        release: '8.4'
        force_register: false
        auto_attach: true
        state: present
      when: subscription_status.rc == 1

    # ansible-2.8-for-rhel-8-x86_64-rpms
    - name: Add ansible-2.9-for-rhel-8-x86_64-rpms repo
      command: subscription-manager repos --enable ansible-2.9-for-rhel-8-x86_64-rpms
      changed_when: false

    - name: Uninstall ansible
      dnf:
        name: ansible
        state: absent

