---
- hosts: localhost
  connection: local
  become: yes

  vars_prompt:
    - name: username
      prompt: What is your RHEL username?
      private: false

    - name: password
      prompt: What is your RHEL password?

  tasks:

    - name: Check subscription status
      command: subscription-manager service-level
      register: subscription_status
      changed_when: false
      check_mode: false

    - name: Register with Red Hat subscription
      redhat_subscription:
        username: "{{ username }}"
        password: "{{ password }}"
        release: '8.4'
        force_register: false
        auto_attach: true
        state: present
      when: subscription_status.rc == 1
