---
- hosts: all
  become: true

  tasks:

    - name: Creates /data/backup
      file:
        path: /data/backup
        state: directory
        mode: g+x,o+x
      when: '"webservers" in group_names'

    - name: Create /etc/server_role
      copy: 
        dest: /etc/server_role
        content: "{{ group_names | string | regex_search('webservers|databases')}}"

    - name: Cheks if httpd is installed
      command: rpm -qa | grep -qE '^httpd-[0-9]'
      args:
        warn: false
      register: httpd_install_status
      changed_when: false
      when: '"webservers" in group_names or "databases" in group_names'
  
    - name: Shows httpd package as installed
      debug:
        msg: "HTTPD is installed"
      when: 
        - 'httpd_install_status.rc == 0 and
          ("webservers" in group_names or "databases" in group_names)'
  
    - name: Shows httpd package as not installed
      debug:
        msg: "HTTPD is not installed"
      when: 
        - 'httpd_install_status.rc != 0 and
          ("webservers" in group_names or "databases" in group_names)'

    - name: Makes sure default target is multi-user.target
      shell: |
          if ! systemctl get-default | grep -q multi-user.target ; then
            systemctl set-default multi-user.target
            /bin/false
          else
            exit 0
          fi
      register: targetlevel_output
      changed_when: targetlevel_output.rc == 1
      ignore_errors: true
      

